name: Deno CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: # Allow manual triggering

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deno-version: [1.38.x, 1.x] # Test against specific version and latest

    name: Deno ${{ matrix.deno-version }}
    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno-version }}

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.deno
            ~/.cache/deno
          key: ${{ runner.os }}-deno-${{ hashFiles('deno.lock') }}
          restore-keys: |
            ${{ runner.os }}-deno-

      - name: Verify formatting
        run: deno task fmt:check

      - name: Run linter
        run: deno task lint

      - name: Check types
        run: deno task check

      - name: Run tests
        run: deno task test
        env:
          # Use dummy API keys for testing
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY || 'sk-dummy-key-for-testing' }}
          TAVILY_API_KEY: ${{ secrets.TAVILY_API_KEY || 'dummy-key-for-testing' }}
          # Test mode flag to avoid calling real APIs
          TEST_MODE: true
